### ISSUE TITLE
0.3 is not yet available in the cargo index

### ISSUE THREAD

**Issue by thedrow** [nbaksalyar/rust-streaming-http-parser#15]
Can you please make a new release?

**Comment by nbaksalyar** [comment]
Yes, sorry, the current master branch hasn't been finalized yet: there's some missing documentation and builds fail on Windows.

But if you're already using it, I'm going to finish and publish it on crates.io today.

Thanks!

**Comment by nbaksalyar** [comment]
OK, now it's available at [crates.io](https://crates.io/crates/http-muncher).

Please let me know if you find any issues.
Thank you! :)

**Comment by thedrow** [comment]
Thanks!
