### ISSUE TITLE
Documentation needs to be updated with the 3.0 API

### ISSUE THREAD

**Issue by breakds** [nbaksalyar/rust-streaming-http-parser#16]
I found that the documentation is out of date. What I have noticed is that in version 3.0, `Parser::request()` does not accept the handler any more. Instead, the handler is fed at the point when `Parser::parse()` is called, which makes `Parser::parse()` accept one more argument.

**Comment by nbaksalyar** [comment]
You're right, this should be fixed. Thanks!
